port 26379
sentinel monitor talentnest-redis redis 6379 2
sentinel down-after-milliseconds talentnest-redis 5000
sentinel parallel-syncs talentnest-redis 1
sentinel failover-timeout talentnest-redis 10000
sentinel auth-pass talentnest-redis ${REDIS_PASSWORD:-talentnest}
