global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'talentnest-api'
    static_configs:
      - targets: ['backend:3001']
    metrics_path: /metrics
    scheme: http

  - job_name: 'talentnest-redis'
    static_configs:
      - targets: ['redis:6379']

  - job_name: 'talentnest-postgres'
    static_configs:
      - targets: ['postgres:5432']

  - job_name: 'talentnest-node'
    static_configs:
      - targets: ['backend:3001']
    metrics_path: /metrics
